alias rmdb="find . -name \*\'s\ conflicted\ copy\ \* -exec rm  {} \;"
alias djrun="python manage.py runserver_plusi 0.0.0.0:8000"
alias server="python -m SimpleHTTPServer 9999"
alias upd="sudo apt-get update && sudo apt-get dist-upgrade"
alias psql="sudo -u postgres psql deepsouthsounds"
